import Head from 'next/head'
import Image from 'next/image'
import Navbar from "../components/Navbar"
import HeroImg from '@/components/HeroImg'
import Courses from '@/components/Courses'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Webloom | Educational site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar></Navbar>
      </header>

      <main>
        <HeroImg></HeroImg>
        <Courses></Courses>
        <Contact></Contact>
      </main>

    </div>
  )
}
